export default {
    SUCCESS: 'The opration has been successful',
    ERROR: 'The opration has an error',
    PRODUCT_CREATED: 'Product created successfully',
    PRODUCT_UPDATED: 'Product updated successfully',
    PRODUCT_DELETED: 'Product deleted successfully',
    PRODUCT_NOT_FOUND: 'Product not found',
    VARIANT_CREATED: 'Variant created successfully',
    VARIANT_UPDATED: 'Variant updated successfully',
    VARIANT_DELETED: 'Variant deleted successfully',
    VARIANT_NOT_FOUND: 'Variant not found',
    ORDER_CREATED: 'Order created successfully',
    ORDER_UPDATED: 'Order updated successfully',
    ORDER_NOT_FOUND: 'Order not found',
    SOURCE_BATCH_CREATED: 'Source batch created successfully',
    SOURCE_BATCH_UPDATED: 'Source batch updated successfully',
    SOURCE_BATCH_DELETED: 'Source batch deleted successfully',
    SOURCE_BATCH_NOT_FOUND: 'Source batch not found',
    INSUFFICIENT_SOURCE_ML: 'Insufficient ml in source batch',
    VENDOR_CREATED: 'Vendor created successfully',
    VENDOR_UPDATED: 'Vendor updated successfully',
    VENDOR_DELETED: 'Vendor deleted successfully',
    VENDOR_NOT_FOUND: 'Vendor not found',
    DECANT_SESSION_CREATED: 'Decant session created successfully',
    DECANT_SESSION_NOT_FOUND: 'Decant session not found',
    DECANT_STOCK_NOT_FOUND: 'Decant stock not found',
    SHOPIFY_SYNC_STARTED: 'Shopify sync started',
    SYNC_NO_NEW_PRODUCTS: 'No new products to sync',
    SYNC_NO_NEW_ORDERS: 'No new orders to sync',
    INVALID_WEBHOOK: 'Invalid webhook signature',
    WEBHOOK_PROCESSED: 'Webhook processed successfully',
    PURCHASE_CREATED: 'Purchase created successfully',
    PURCHASE_UPDATED: 'Purchase updated successfully',
    PURCHASE_DELETED: 'Purchase deleted successfully',
    PURCHASE_NOT_FOUND: 'Purchase not found',
    SYNC_PRODUCTS_STARTED: 'Shopify product sync started',
    SHIPMENT_CREATED: 'Shipment created successfully',
    SHIPMENT_NOT_FOUND: 'Shipment not found',
    AWB_ASSIGNED: 'AWB assigned successfully',
    SHIPMENT_ALREADY_EXISTS: 'Shipment already exists for this order',
    TRACKING_UPDATED: 'Tracking updated successfully',
    SHIPROCKET_ERROR: 'ShipRocket API error',
    EXPENSE_CREATED: 'Expense created successfully',
    EXPENSE_UPDATED: 'Expense updated successfully',
    EXPENSE_DELETED: 'Expense deleted successfully',
    EXPENSE_NOT_FOUND: 'Expense not found',
    REMITTANCE_CREATED: 'Remittance created successfully',
    REMITTANCE_UPDATED: 'Remittance updated successfully',
    REMITTANCE_DELETED: 'Remittance deleted successfully',
    REMITTANCE_NOT_FOUND: 'Remittance not found'
}
